name: CI-SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: arjen
          server: 194.59.158.13
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: '/home/arjen/juicify'
          args: '-o ConnectTimeout=5'

  restart-dockers:
    runs-on: ubuntu-latest
    needs: deploy-via-sftp

    steps:
      - name: Restarting dockers related to deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd juicify && cd client && npm i && npx prisma generate && cd .. && docker-compose -f docker-compose.yml up --build -d --force-recreate && docker system prune --all --force --volumes
          host: 194.59.158.13
          port: 22
          username: arjen
          passphrase: ${{ secrets.FTP_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
